report:
  sendIngame: true
  sendDiscord: true
  discordChannel: reports
  discordRole: Moderator
  pingModerators: true
  addToWatchlist: true
watchlist:
  playerJoinNotification:
    sendIngame: true
    sendDiscord: true
  discordChannel: reports
  pingModerators: true
  tabListPrefix: "#ff8866W"
