report:
  sendIngame: true
  sendDiscord: true
  discordChannel: reports
  discordRole: Moderator
  pingModerators: false
  addToWatchlist: true
watchlist:
  playerJoinNotification:
    sendIngame: true
    sendDiscord: true
    discordChannel: reports
    pingModerators: false
  tabListPrefix: "#ff8866W"
